name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build-and-push-rustci-image:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境运行
    permissions:
      contents: read
      packages: write  # 授予推送镜像到 GHCR 的权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.rust_ci
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rust_ci:latest
